### ISSUE TITLE
what program you have used to manage you dotfiles

### ISSUE THREAD

**Issue by ghost** [BurntSushi/dotfiles#1]

**Comment by BurntSushi** [comment]
Not sure what you mean. I don't use any program. Just git. Can you say more?

**Comment by ghost** [comment]
how do you use git to do this?
can you write about it?

**Comment by BurntSushi** [comment]
I clone the repository in my home directory:

```
$ git init
$ git remote add origin git@github.com:BurntSushi/dotfiles
$ git pull origin master
```

That's it.

**Comment by ghost** [comment]
instead of having a .gitignore file you can set `status.showUntrackedfile no` and manually add the files you need.

**Comment by BurntSushi** [comment]
@mobop Yes, I know. I used to do that. [But I want to see untracked files.](https://github.com/BurntSushi/dotfiles/blob/7f8da52a008b81d758920b065d379f478c5a8937/.gitignore#L1-L3) Otherwise, it's too easy to forget to add a new file to git.
