### ISSUE TITLE
case option makes later option never match

### ISSUE THREAD

**Issue by indygwyn** [BurntSushi/dotfiles#4]
https://github.com/BurntSushi/dotfiles/blob/965383e6eeb0bad40d10448ce57f040825f735a7/bin/github-link#L23

line 22 will preclude line 23 every being matched, probably should swap those 2 lines

**Comment by BurntSushi** [comment]
Yeah shellcheck bleated about this just today and I haven't pushed the fix yet. I'm not sure why it didn't get caught before. Thanks for the notice. :-)
